import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),output=process.env.QA_OUTPUT||'/tmp/krane-review-round';await mkdir(output,{recursive:true});
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!path.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2'})[extname(path)]||'application/octet-stream');res.end(await readFile(path))}catch{res.writeHead(404).end()}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.KRANE_BASE||`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH});const results=[];
async function test(name,fn){if(process.argv[2]&&!name.includes(process.argv[2]))return;const context=await browser.newContext({viewport:{width:390,height:844}});context.setDefaultTimeout(6000);context.setDefaultNavigationTimeout(15000);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await fn(page);assert.equal(errors.length,0,errors.join('; '));results.push({name,status:'pass'});console.log('PASS',name)}catch(e){results.push({name,status:'fail',error:e.message});console.log('FAIL',name,e.message.slice(0,200));await page.screenshot({path:output+'/'+name+'.png',fullPage:true}).catch(()=>{})}finally{await context.close()}}
async function open(p,id,entry='direct'){await p.goto(`${base}/b2c/krane-b2c.html?public=1&screens=1&fresh=1&entry=${entry}&demoStage=${id}#${id}`,{waitUntil:'domcontentloaded'});await p.locator('#'+id+'.active').waitFor();await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(700);}
try{
await test('all-category-view-audit',async p=>{await open(p,'intake1');const rows=await p.evaluate(()=>{const rows=[];for(const category of ['hair-skin','skin','weight','sexual-health','sleep-stress','hormone','general']){setSelectedCategory(category);renderIntakeQuestions();for(const el of document.querySelectorAll('section.screen[id]'))rows.push({category,route:el.id,canonical:KraneReviewTools.canonicalRoutes[el.id]||el.id,sid:KraneReviewTools.screenIds[el.id],text:(el.querySelector('.screen__body')?.textContent||el.textContent).replace(/\s+/g,' ').trim()});}return rows;});await writeFile('/tmp/krane-all-category-audit.json',JSON.stringify(rows,null,2));assert.equal(rows.length,441);});
await test('review-route-context',async p=>{await p.setViewportSize({width:1440,height:900});await open(p,'intake-concern','partner');await p.locator('.rail [data-go="intake4"]').evaluate(el=>el.click());await p.locator('#intake4.active').waitFor();assert.equal(await p.evaluate(()=>KraneReviewTools.screenIds['partner-patient-info']),await p.evaluate(()=>KraneReviewTools.screenIds['patient-info']));});
await test('shared-payment-markup',async p=>{await open(p,'payment-gw');assert.equal(await p.locator('[data-shared-gateway] .gateway').count(),2);assert.equal(await p.locator('#payment-gw #medication-card-number').count(),1);assert.equal(await p.locator('#consultpay-gw #consult-card-number').count(),1);assert.equal(await p.locator('#payment-gw [data-consult-payment-total]').count(),0);});
await test('tracking-shared-width',async p=>{for(const width of [390,1440]){await p.setViewportSize({width,height:900});await open(p,'payment');const pay=await p.locator('#payment>.screen__body').boundingBox();await open(p,'tracking');const track=await p.locator('#tracking>.screen__body').boundingBox();assert(Math.abs(pay.width-track.width)<2);assert(await p.locator('#tracking').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:'/tmp/krane-tracking-'+width+'.png'});}});
await test('crane-animation-loaded',async p=>{await open(p,'preloader');const img=p.locator('.ks-paper-crane-live');const seen=new Set();for(let i=0;i<8;i++){assert(await img.evaluate(e=>e.complete&&e.naturalWidth>0));seen.add(await img.getAttribute('src'));await p.waitForTimeout(400);}assert(seen.size>1);assert(await p.locator('#preloader.active').count());await p.screenshot({path:'/tmp/krane-crane-after.png'});});
await test('saved-address-actions',async p=>{await open(p,'address');await p.evaluate(()=>{rememberDeliveryAddress({label:'QA address',recipientFirstName:'Test',recipientLastName:'User',recipientPhone:'0812345678',building:'1',line:'Test road',province:'กรุงเทพมหานคร',districtName:'ปทุมวัน',subdistrict:'ลุมพินี',postcode:'10330'});setAddressPageMode('list');renderAddressList();});const edit=p.locator('[data-address-edit]').first(),del=p.locator('[data-address-delete]').first();const a=await edit.boundingBox(),b=await del.boundingBox();assert(Math.abs(a.y-b.y)<1);assert.equal(await edit.locator('svg').count(),1);assert.equal(await del.locator('svg').count(),1);await p.screenshot({path:'/tmp/krane-address-actions.png'});});
}finally{await writeFile(output+'/results.json',JSON.stringify(results,null,2));await browser.close();server.close()}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
