#!/usr/bin/env bash
# Regenerates the three teal palette variants from the base landing page.
# Run after any edit to krane-b2c-landing.html so the variants stay in sync.
# Usage: bash palettes/build.sh   (run from Krane-Clinic/public/b2c/)
set -e
BASE="krane-b2c-landing.html"
for P in a b c; do
  OUT="krane-b2c-landing-teal-$P.html"
  python3 - "$BASE" "$OUT" "$P" <<'PY'
import sys
base, out, p = sys.argv[1], sys.argv[2], sys.argv[3]
html = open(base, encoding='utf-8').read()
inject = (
    f'<!-- PALETTE VARIANT {p.upper()}. Generated by palettes/build.sh.\n'
    f'     Do not edit this file. Edit {base} or palettes/teal-{p}.css and rerun the script. -->\n'
    f'<link rel="stylesheet" href="palettes/_treatment.css">\n'
    f'<link rel="stylesheet" href="palettes/teal-{p}.css">\n'
)
html = html.replace('</head>', inject + '</head>', 1)
open(out, 'w', encoding='utf-8').write(html)
print("wrote", out)
PY
done
