/* ============================================================
   KRANE marketing pages: Thai source -> English.

   The landing page translates [data-i18n] elements and the service pages
   translate [data-nav-i18n] in the header. Everything else on those pages is
   Thai written straight into the markup, so English mode used to leave most of
   the page in Thai (client audit, 19 Aug). This walks the remaining text and
   swaps it, keyed on the exact Thai string, and puts the Thai back when the
   page returns to Thai.

   It is deliberately additive: it never touches a node that another handler
   already translated, because that node is no longer Thai.
   ============================================================ */
(function () {
  var EN = {
    /* Labels the screen reader speaks and the carousel controls, none of
       them a text node, so the walk above never saw them. Found once the
       contract check started reading attributes too (31 Aug). */
    "เมนูหลัก":"Main menu",
    "เมนูมือถือ":"Mobile menu",
    "ปิดเมนู":"Close menu",
    "เปิดเมนู":"Open menu",
    "เปิดเมนูโปรไฟล์":"Open profile menu",
    "การดูแลน้ำหนัก":"Weight care",
    "การดูแลผมและผิว":"Hair and skin care",
    "บริการและข้อมูลเพิ่มเติม":"Services and more",
    "จุดเด่นของ Krane":"What sets Krane apart",
    "จุดเด่นของการดูแลกับ Krane":"What sets care with Krane apart",
    "ขั้นตอนการใช้บริการ 3 ขั้นตอน":"How it works, in three steps",
    "เลือกขั้นตอน":"Choose a step",
    "ขั้นตอนก่อนหน้า":"Previous step",
    "ขั้นตอนถัดไป":"Next step",
    "ขั้นตอนที่ 1":"Step 1",
    "ขั้นตอนที่ 2":"Step 2",
    "ขั้นตอนที่ 3":"Step 3",
    "อยากให้เราช่วยดูแล":"What would you like help with",
    "เรื่องไหนมากที่สุด?":"the most?",
    "เส้นผมและหนังศีรษะ":"Hair and scalp",
    "ถัดไป":"Next",
    "ปรึกษาแพทย์แบบส่วนตัวผ่านวิดีโอ เสียง หรือแชท พร้อมรับคำแนะนำที่เหมาะกับคุณ":"Speak privately with a doctor by video, voice or chat, and receive advice tailored to you.",
    "รับแผนการรักษา ติดตามผลกับแพทย์ และจัดส่งยาแท้ในบรรจุภัณฑ์มิดชิดถึงบ้าน":"Receive your treatment plan, follow up with your doctor, and have authentic medicine delivered discreetly to your door.",
    "ติดตามการจัดส่ง":"Track delivery",
    "พัสดุกำลังเดินทาง":"Your parcel is on its way",
    "คาดว่าจะถึงคุณภายในวันนี้":"Expected to arrive today",
    "ขั้นตอนที่ 1 ตอบแบบประเมิน":"Step 1: answer the assessment",
    "ขั้นตอนที่ 2 คุยกับแพทย์":"Step 2: talk to a doctor",
    "ขั้นตอนที่ 3 รับการดูแลถึงบ้าน":"Step 3: care delivered to your door",
    "กลับไปขั้นตอนที่ 1 ตอบแบบประเมิน":"Back to step 1: answer the assessment",
    "ไปขั้นตอนที่ 2 คุยกับแพทย์":"Go to step 2: talk to a doctor",
    "ไปขั้นตอนที่ 3 รับการดูแลถึงบ้าน":"Go to step 3: care delivered to your door",
    "เลื่อนดูตัวเลือกการดูแล":"Browse care options",
    "ตัวเลือกก่อนหน้า":"Previous option",
    "ตัวเลือกถัดไป":"Next option",
    "รายการตัวเลือกการดูแลแบบเลื่อนได้":"Scrollable care options",
    "ความเห็นก่อนหน้า":"Previous testimonial",
    "เลือกความเห็น":"Choose a testimonial",
    "ความเห็นที่ 1":"Testimonial 1",
    "ความเห็นที่ 2":"Testimonial 2",
    "ความเห็นที่ 3":"Testimonial 3",
    "ความเห็นที่ 4":"Testimonial 4",
    "ความเห็นถัดไป":"Next testimonial",
    "การดูแลน้ำหนักตั้งแต่เริ่มต้นจนถึงการติดตาม":"Weight care from the first visit through follow-up",
    "ตัวอย่างการติดตามเส้นผม":"An example of hair progress tracking",
    "มาตรฐานระบบของ INET":"INET system standards",
    "ผลลัพธ์ก่อนและหลังการติดตามน้ำหนัก":"Before-and-after weight-care progress",
    "ผลลัพธ์คู่ก่อนหน้า":"Previous result pair",
    "ผลลัพธ์คู่ถัดไป":"Next result pair",
    "เลือกผลลัพธ์ก่อนและหลัง":"Choose a before-and-after result",
    "ผลลัพธ์คู่ที่ 1":"Result pair 1",
    "ผลลัพธ์คู่ที่ 2":"Result pair 2",
    "ผลลัพธ์คู่ที่ 3":"Result pair 3",
    "ปิดประวัติแพทย์":"Close doctor profile",
    "ปิดรีวิว":"Close review",
    "ปรึกษาแพทย์ฟรีและเริ่มการดูแลออนไลน์":"Free doctor consultation, care started online",
    "เริ่มการดูแลตามเรื่องที่สนใจ":"Start care with what you came for",
    "ข้ามไปยังเนื้อหาหลัก":"Skip to main content",
    "จัดส่งยาได้ทั่วประเทศ":"Nationwide medicine delivery",
    "ปรึกษาหมอส่วนตัว 1 ต่อ 1":"Private 1-to-1 doctor consultation",
    "แพทย์มีใบอนุญาต":"Licensed doctors",
    "เริ่มทันที 100% ออนไลน์":"Start instantly, 100% online",
    "เวลาทำการ 09:00-24:00 น.":"Open daily 09:00-24:00",
    "เปิดให้บริการทุกวัน":"Open every day",
    "เริ่มง่าย ๆ เพียง 3 ขั้นตอน":"Three simple steps",
    "เลือกเรื่องที่กังวลและตอบคำถามสุขภาพเบื้องต้น ใช้เวลาเพียง 1–2 นาที":"Choose what concerns you and answer a short health questionnaire. It takes just 1–2 minutes.",
    "มิติใหม่ในการลดน้ำหนัก":"A new approach to weight loss",
    /* The weight and hair sections split their headings and testimonial
       credits across several elements, so the whole-string keys above no
       longer match a single text node. Each visible piece needs its own key. */
    "มิติใหม่ในการ":"A new approach to",
    "ลดน้ำหนัก":"weight loss",
    "GLP-1 แบบรับประทาน":"Oral GLP-1",
    "แบบรับประทาน":"Oral",
    "ตัวเลือกแบบเม็ดที่แพทย์อาจพิจารณาตามสุขภาพและเป้าหมาย":"A tablet option your doctor may consider, based on your health and goals",
    "ติดตามผลต่อเนื่อง":"Ongoing follow-up",
    "คุณ ก., 39 ปี":"K., 39",
    "คุณ ต., 34 ปี":"T., 34",
    "คุณ ธ., 45 ปี":"Th., 45",
    "คุณ น., 38 ปี":"N., 38",
    "คุณ พ., 36 ปี":"P., 36",
    "คุณ ม., 38 ปี":"M., 38",
    "คุณ ม., 41 ปี":"M., 41",
    "คุณ ร., 42 ปี":"R., 42",
    "คุณ ว., 41 ปี":"W., 41",
    "คุณ อ., 33 ปี":"O., 33",
    "เริ่มทันที":"Start now",
    "เรียนรู้เพิ่มเติม":"Learn more",
    "ทางเลือกที่แพทย์อาจพิจารณา":"Options your doctor may consider",
    "ตัวเลือกที่เหมาะกับแต่ละคน":"Options tailored to each person",
    "รายชื่อยาตามแพทย์พิจารณา":"Medicines your doctor may consider",
    "ตัวเลือกยาสำหรับการควบคุมน้ำหนัก":"Weight-management medicine options",
    "ฉีดสัปดาห์ละครั้ง":"Once-weekly injection",
    "มีขนาด 2.5, 5, 7.5, 10, 12.5 และ 15 mg":"Available in 2.5, 5, 7.5, 10, 12.5 and 15 mg",
    "มีขนาด 0.25, 0.5 และ 1 mg/โดส":"Available in 0.25, 0.5 and 1 mg per dose",
    "มีขนาด 0.25, 0.5, 1, 1.7 และ 2.4 mg":"Available in 0.25, 0.5, 1, 1.7 and 2.4 mg",
    "มีขนาด 3, 7 และ 14 mg":"Available in 3, 7 and 14 mg",
    "ดูรายละเอียด":"View details",
    "แพทย์ประเมิน":"Doctor assessed",
    "เฉพาะบุคคล":"Personalised",
    "แผนดูแลเฉพาะบุคคล":"Personalised care plan",
    "เริ่มจากข้อมูลสุขภาพและเป้าหมายของคุณ":"Starts with your health and your goals",
    "รายสัปดาห์":"Weekly",
    "ทางเลือก GLP-1":"GLP-1 options",
    "แพทย์พิจารณาความเหมาะสมและติดตามผล":"Your doctor assesses suitability and follows up",
    "ดูความเหมาะสม":"Check suitability",
    "ติดตามผล":"Follow-up",
    "ต่อเนื่อง":"Ongoing",
    "ติดตามและปรับแผน":"Follow up and adjust your plan",
    "ทบทวนการตอบสนองร่วมกับแพทย์เป็นระยะ":"Review your response with your doctor regularly",
    "ควบคู่การรักษา":"Alongside treatment",
    "เป้าหมายเล็ก ๆ ที่ทำต่อได้ในชีวิตจริง":"Small, sustainable goals for everyday life",
    "เริ่มต้น":"Get started",
    "รายเดือน":"Monthly",
    "ปรับการดูแลเมื่อสุขภาพและเป้าหมายเปลี่ยน":"Adjust care as your health and goals change",
    "*ตัวเลือกยาและแผนการดูแลขึ้นอยู่กับการประเมินของแพทย์ ไม่ใช่ทุกตัวเลือกจะเหมาะกับทุกคน":"*Medication and care options depend on a doctor's assessment. Not every option is suitable for everyone.",
    "Quick input · ใช้เวลาไม่ถึง 1 นาที":"Quick input · under 1 minute",
    "เป้าหมายของคุณ?":"What's your goal?",
    "ลดความอยากอาหาร":"Reduce appetite",
    "ยังไม่แน่ใจ":"Not sure yet",
    "คำตอบจะพาคุณไปเริ่มแบบประเมินสุขภาพ":"Your answer takes you to the health assessment",
    "เสียงจากผู้รับการดูแล":"What people say about their care",
    "เรื่องน้ำหนัก":"Weight care",
    "“พอมีแพทย์ช่วยดูแลเรื่องความอยากอาหารและติดตามผล แผนลดน้ำหนักก็ชัดเจนขึ้น”":"“Having a doctor help with appetite and follow-up made my weight-care plan feel much clearer.”",
    "ผู้รับการดูแลด้านน้ำหนัก · ติดตามผลต่อเนื่อง":"Weight-care patient · ongoing follow-up",
    "“ปรึกษาออนไลน์สะดวก ไม่ต้องเดินทาง และคุยเรื่องน้ำหนักกับแพทย์ได้แบบเป็นส่วนตัว”":"“Online consultation is convenient. I can discuss my weight privately with a doctor without travelling.”",
    "ผู้รับการดูแลด้านน้ำหนัก · ปรึกษาออนไลน์":"Weight-care patient · online consultation",
    "“การติดตามเป็นระยะช่วยให้รู้ว่าควรปรับพฤติกรรมตรงไหน เพื่อให้ทำต่อได้จริง”":"“Regular follow-ups help me see which habits to adjust so I can keep going.”",
    "ผู้รับการดูแลด้านน้ำหนัก · ปรับพฤติกรรม":"Weight-care patient · habit change",
    "“ชอบที่แผนเริ่มจากสุขภาพของเรา ไม่ได้ใช้สูตรเดียวกันกับทุกคน”":"“I like that the plan starts with my health instead of using the same formula for everyone.”",
    "ผู้รับการดูแลด้านน้ำหนัก · แผนเฉพาะบุคคล":"Weight-care patient · personalised plan",
    "ผลลัพธ์จากการติดตาม":"Progress over time",
    "ติดตามการเปลี่ยนแปลงอย่างเป็นระบบ":"Track progress consistently",
    "น้ำหนัก · ติดตามผลตามระยะเวลาที่แพทย์แนะนำ":"Weight · follow-up on your doctor's recommended schedule",
    "ภาพช่วงก่อนเริ่มแผนดูแลน้ำหนัก คู่ที่ 1":"Before starting weight care, pair 1",
    "ภาพช่วงติดตามผลแผนดูแลน้ำหนัก คู่ที่ 1":"Weight-care follow-up, pair 1",
    "ภาพช่วงก่อนเริ่มแผนดูแลน้ำหนัก คู่ที่ 2":"Before starting weight care, pair 2",
    "ภาพช่วงติดตามผลแผนดูแลน้ำหนัก คู่ที่ 2":"Weight-care follow-up, pair 2",
    "ภาพช่วงก่อนเริ่มแผนดูแลน้ำหนัก คู่ที่ 3":"Before starting weight care, pair 3",
    "ภาพช่วงติดตามผลแผนดูแลน้ำหนัก คู่ที่ 3":"Weight-care follow-up, pair 3",
    "ผมหนา ผ่านวิธีที่พิสูจน์มาแล้ว":"Thicker hair, with proven approaches",
    "การดูแลที่เลือกได้ตามสาเหตุและเป้าหมาย":"Care chosen around the cause and your goals",
    "แข็งแรงกว่าเดิม":"Feel stronger again",
    "ทางเลือกที่แพทย์พิจารณาให้เหมาะกับคุณ":"Options selected by your doctor for you",
    "เม็ดยาสีน้ำเงินแบบไม่แสดงตราสินค้า":"Unbranded blue tablets",
    "ปลอดภัยตามมาตรฐานสากล":"Protected to international standards",
    "โครงสร้างพื้นฐานโดย INET พร้อมมาตรฐาน ISO ครบ 3 ด้าน":"INET infrastructure certified across three ISO standards",
    "*ภาพประกอบเพื่อสื่อรูปแบบการติดตาม ผลลัพธ์แตกต่างกันในแต่ละบุคคล":"*Images illustrate the follow-up format. Results vary by individual.",
    "เส้นผม · อ่าน 5 นาที":"Hair · 5 min read",
    "ดูแลเส้นผมอย่างไรให้แผนการรักษาไปได้ไกลกว่าเดิม":"How to make your hair-care plan last",
    "เริ่มปรึกษาแพทย์วันนี้":"Start your consultation today",
    "ใช้เวลาเพียง 5 นาทีในการกรอกแบบประเมินดิจิทัลและเริ่มสนทนาทางการแพทย์โดยตรงกับแพทย์เฉพาะทาง":"Complete a five-minute digital assessment and start a private consultation with a specialist.",
    "โซลูชันทางคลินิกระดับพรีเมียมสำหรับผู้ชายยุคใหม่ ขับเคลื่อนด้วยวิทยาศาสตร์การแพทย์ ปรับแต่ละอย่างเป็นส่วนตัวเพื่อสนับสนุนเส้นทางสุขภาพของคุณ":"Premium clinical care for modern men, grounded in medical science and personalised around your health journey.",
    "TRT & ความยืนยาว":"TRT & longevity",
    "การรับประกันของเรา":"Our guarantee",
    "ที่ปรึกษาทางการแพทย์":"Medical advisers",
    "ร่วมงานกับเรา":"Careers",
    "สื่อมวลชน":"Press",
    "ข้อกำหนดการใช้บริการ":"Terms of service",
    "ความยินยอมของผู้ป่วย":"Patient consent",
    "ศูนย์ช่วยเหลือ":"Help centre",
    "ยาผ่านการรับรองจาก อย.":"Thai FDA-approved medicine",
    "แผนการรักษาเฉพาะบุคคล":"Personalised treatment plans",
    "บรรจุภัณฑ์มิดชิด":"Discreet packaging",
    "พญ. กรผกา ขันติโกสุม ว.":"Dr. Kornpaka Khantikosum, MD",
    "นพ. ไพรัช เกตุรัตนกุล ว.":"Dr. Pairat Ketrattanakul, MD",
    "อ.นพ. พหล สโรจวิสุทธิ์ ว.":"Dr. Pahol Sarojwisut, MD",
    "อ.นพ. ชวลิต หงส์เลิศสกุล ว.":"Dr. Chawalit Hongloetsakul, MD",
    "แพทย์ที่ปรึกษา Krane · เส้นผมและผิวหนัง":"Krane consulting doctor · hair and skin",
    "แพทย์ที่ปรึกษา Krane · การลดน้ำหนัก":"Krane consulting doctor · weight management",
    "แพทย์ที่ปรึกษา Krane · สุขภาพทางเพศ":"Krane consulting doctor · sexual health",
    "แพทย์ที่ปรึกษา · เส้นผมและผิวหนัง":"Consulting doctor · hair and skin",
    "แพทย์ที่ปรึกษา · การลดน้ำหนัก":"Consulting doctor · weight management",
    "แพทย์ที่ปรึกษา · สุขภาพทางเพศ":"Consulting doctor · sexual health",
    "ผู้อำนวยการแพทย์":"Medical director",
    "โภชนศาสตร์คลินิก":"Clinical nutrition",
    "ศัลยศาสตร์ยูโรวิทยา":"Urological surgery",
    "ตจวิทยา (ผิวหนัง)":"Dermatology",
    "ดูประวัติเต็ม":"See full profile",
    "ดูประวัติเต็ม →":"See full profile →",
    "ดูประวัติ พญ. กรผกา ขันติโกสุม":"See Dr. Kornpaka Khantikosum's profile",
    "ดูประวัติ นพ. ไพรัช เกตุรัตนกุล":"See Dr. Pairat Ketrattanakul's profile",
    "ดูประวัติ อ.นพ. พหล สโรจวิสุทธิ์":"See Dr. Pahol Sarojwisut's profile",
    "ดูประวัติ อ.นพ. ชวลิต หงส์เลิศสกุล":"See Dr. Chawalit Hongloetsakul's profile",
    "แพทย์ก่อนหน้า":"Previous doctor",
    "แพทย์ถัดไป":"Next doctor",
    "ทีมแพทย์ของเรา":"Our doctors",
    "การดูแลของ Krane ออกแบบและทบทวนโดยทีมแพทย์เฉพาะทางที่ได้รับใบอนุญาต ทุกแผนเริ่มจากข้อมูลสุขภาพจริงของคุณ และปรับตามความเหมาะสมทางคลินิกเมื่อข้อมูลเปลี่ยนไป":"Krane's care is designed and reviewed by licensed specialists. Every plan starts from your own health information and is adjusted on clinical grounds as that information changes.",
    "วิธีที่ทีมแพทย์ร่วมออกแบบการดูแล":"How the doctors shape your care",
    "ทุกขั้นตอนเริ่มจากข้อมูลสุขภาพจริง และผ่านการพิจารณาทางการแพทย์ก่อนเสนอทางเลือกที่เหมาะสม":"Every step starts from real health information and is reviewed clinically before any option is offered.",
    "รอรูปจาก workshop":"Awaiting images from the workshop",
    "เริ่มจากเรื่องที่คุณกังวล":"Start with what concerns you",
    "แบบประเมินรวบรวมอาการ ประวัติสุขภาพ และเป้าหมาย เพื่อให้แพทย์เห็นภาพรวมก่อนเริ่มปรึกษา":"The questionnaire gathers your symptoms, health history and goals so the doctor sees the whole picture before the consultation.",
    "ทบทวนทางเลือกอย่างมีเหตุผล":"Weigh the options with reasons",
    "แพทย์อธิบายประโยชน์ ข้อควรระวัง และทางเลือก โดยการสั่งยาขึ้นอยู่กับความเหมาะสมทางคลินิกของแต่ละคน":"The doctor explains the benefits, the cautions and the alternatives. Whether medicine is prescribed depends on what is clinically appropriate for you.",
    "ติดตามและปรับแผนต่อเนื่อง":"Follow up and adjust",
    "ทีมแพทย์ใช้ข้อมูลติดตามผลเพื่อประเมินความคืบหน้า ความปลอดภัย และปรับแผนเมื่อสุขภาพหรือเป้าหมายเปลี่ยนไป":"The doctors use your follow-up data to judge progress and safety, and adjust the plan when your health or goals change.",
    "บทความสุขภาพ":"Health articles",
    "ทำความเข้าใจกลไก ระยะเวลาที่เห็นผล และข้อควรระวังก่อนเริ่มใช้":"How it works, how long results take, and what to watch for before starting.",
    "วิธีใช้ให้ถูกต้อง ผลข้างเคียงที่พบได้ และช่วงเวลาที่ควรประเมินซ้ำ":"How to use it correctly, the side effects you may see, and when to reassess.",
    "การนอน อาหาร และความเครียด ส่งผลต่อวงจรเส้นผมอย่างไร":"How sleep, diet and stress affect the hair cycle.",
    "เริ่มจากข้อมูลสุขภาพจริงของคุณ":"Start from your own health information",
    "ปรึกษาแพทย์เลย":"Talk to a doctor",
    "กลับหน้าหลัก":"Back to home",
    "กลับหน้าแรก":"Back to home",
    "ข้อมูลวิชาชีพและความเชี่ยวชาญอ้างอิงจากข้อมูลที่ Krane Clinic จัดเตรียม และอาจมีการอัปเดตเพิ่มเติม":"Professional details and specialties come from information supplied by Krane Clinic and may be updated.",
    "รายชื่อแพทย์":"Doctor list",
    "เริ่มการดูแล":"Start care",
    "ก่อนและหลังการดูแล":"Before and after care",
    "ภาพติดตามผลถ่ายในมุมและระยะเดิมทุกครั้ง แพทย์เป็นผู้ประเมินความคืบหน้าร่วมกับคุณ":"Follow-up photos are taken at the same angle and distance every time. Your doctor assesses progress with you.",
    "ก่อน":"Before",
    "หลัง":"After",
    "ผมร่วง · ติดตามผล 6 เดือน":"Hair loss · 6-month follow-up",
    "ผิวและสิว · ติดตามผล 3 เดือน":"Skin and acne · 3-month follow-up",
    "น้ำหนัก · ติดตามผล 6 เดือน":"Weight · 6-month follow-up",
    "ตัวอย่างพื้นที่ภาพ รอภาพจริงจากผู้รับบริการที่ยินยอมให้เผยแพร่ · ผลลัพธ์แตกต่างกันในแต่ละบุคคล":"Placeholder images, awaiting real photographs from patients who consent to publication · results vary from person to person",
    "คุณ @bright.mind":"@bright.mind",
    "ผมร่วง":"Hair loss",
    "ผมร่วง · อ่าน 4 นาที":"Hair loss · 4 min read",
    "ผมร่วง · อ่าน 3 นาที":"Hair loss · 3 min read",
    "ฟีนาสเตอไรด์ได้ผลจริงไหม":"Does finasteride really work?",
    "สรุปหลักฐานทางการแพทย์ ผลที่คาดหวังได้ และข้อควรระวังก่อนเริ่มใช้":"The medical evidence in brief, what to expect, and what to watch for before starting.",
    "ไมน็อกซิดิล ต้องคาดหวังอะไรบ้าง":"Minoxidil: what to expect",
    "ไทม์ไลน์การเห็นผลจริง วิธีใช้ให้ต่อเนื่อง และอาการข้างเคียงที่พบบ่อย":"A realistic timeline, how to keep it up, and the common side effects.",
    "ไลฟ์สไตล์":"Lifestyle",
    "ไลฟ์สไตล์ · อ่าน 5 นาที":"Lifestyle · 5 min read",
    "นิสัยดี ๆ เพื่อสุขภาพผม":"Good habits for healthy hair",
    "การนอน อาหาร และความเครียด ส่งผลกับเส้นผมมากกว่าที่คิด":"Sleep, diet and stress affect your hair more than you would think.",
    "น้ำหนัก":"Weight",
    "น้ำหนัก · อ่าน 6 นาที":"Weight · 6 min read",
    "ลดน้ำหนักอย่างปลอดภัยใต้การดูแลแพทย์":"Losing weight safely under a doctor's care",
    "เริ่มจากประเมินสุขภาพ ตั้งเป้าที่ทำได้จริง และติดตามผลเป็นระยะ":"Start with a health assessment, set goals you can actually reach, and review as you go.",
    "ดูบทความทั้งหมด":"See all articles",
    "ทำไมถึงเลือก Krane":"Why choose Krane",
    "บริการอื่น ๆ":"Other services",
    "รีวิวจากสมาชิก":"Member reviews",
    "เปิดรีวิวของ @peach.vlog":"Open @peach.vlog's review",
    "เปิดรีวิวของ @ton_fitlife":"Open @ton_fitlife's review",
    "เปิดรีวิวของ @dr.oak_active":"Open @dr.oak_active's review",
    "เปิดรีวิวของ @bright.mind":"Open @bright.mind's review",
    "เปิดรีวิวของ @mick.antiag":"Open @mick.antiag's review",
    "เปิดรีวิวของ @gun_review":"Open @gun_review's review",
    "กลับไปดูบริการทั้งหมด":"Back to all services",
    "เริ่มประเมิน":"Start the assessment",
    "เริ่มแบบประเมิน":"Start the questionnaire",
    "เริ่มประเมินสุขภาพ":"Start a health assessment",
    "ปรึกษาส่วนตัวกับแพทย์ที่มีใบอนุญาต · ใช้เวลา 5 นาที":"A private consultation with a licensed doctor · about 5 minutes",
    "แพทย์ดูข้อมูลก่อนคุย":"The doctor reviews your information before you talk",
    "ไม่ต้องเริ่มเล่าใหม่ทั้งหมด":"You do not need to start the story again",
    "เป็นส่วนตัว":"Private by design",
    "ปรึกษาออนไลน์จากที่ที่คุณสบายใจ":"Consult online from wherever you feel comfortable",
    "เห็นค่าใช้จ่ายก่อนจ่าย":"See every cost before you pay",
    "แยกค่าปรึกษา ยา และจัดส่งชัดเจน":"Consultation, medicine and delivery are itemised clearly",
    "ดูแลต่อเนื่อง":"Continuous care",
    "ติดตามกับทีมเดิมและปรับแผนได้":"Follow up with the same team and adjust the plan when needed",
    "บริการนี้เหมาะกับคุณไหม":"Is this service right for you?",
    "เช็กภาพรวมก่อนทำแบบประเมิน คำตอบสุดท้ายขึ้นอยู่กับการประเมินของแพทย์":"Review the basics before the questionnaire. The final decision depends on the doctor's assessment.",
    "อาจเหมาะ หากคุณ…":"It may be suitable if you…",
    "มีอาการต่อเนื่องหรือเกิดซ้ำจนกระทบความมั่นใจ":"Symptoms continue or recur and affect your confidence",
    "ต้องการคุยกับแพทย์อย่างเป็นส่วนตัว":"You want to speak with a doctor privately",
    "ต้องการหาสาเหตุ ไม่ใช่ซื้อยาอย่างเดียว":"You want to understand the cause, not just buy medicine",
    "ควรแจ้งแพทย์ก่อน หากคุณ…":"Tell the doctor first if you…",
    "มีอาการเจ็บหน้าอก เหนื่อยผิดปกติ หรือโรคหัวใจ":"Have chest pain, unusual breathlessness or heart disease",
    "ใช้ยากลุ่ม nitrate หรือยาที่ไม่แน่ใจว่าใช้ร่วมกันได้":"Use nitrates or medicine you are unsure can be taken together",
    "มีอาการฉับพลัน รุนแรง หรือการแข็งตัวนานเกิน 4 ชั่วโมง":"Have sudden or severe symptoms, or an erection lasting more than four hours",
    "ตัดสินใจก่อนชำระเงินได้เสมอ":"Decide before you pay",
    "ค่าปรึกษา ค่ายา และค่าจัดส่งจะแสดงแยกรายการให้ตรวจสอบก่อนยืนยัน ไม่มีการสั่งยาโดยอัตโนมัติ":"Consultation, medicine and delivery costs are itemised for review before confirmation. Medicine is never ordered automatically.",
    "เริ่มประเมินก่อน":"Start with an assessment",
    "มีหมอและแผนเดิมดูแลคุณต่อ":"Continue with the same doctor and care plan",
    "ทุกครั้งที่กลับมา ประวัติ แผน และสิ่งที่เคยคุยจะอยู่ในที่เดียว เพื่อให้การติดตามต่อเนื่องและปรับได้จริง":"Whenever you return, your history, plan and previous conversations stay together so follow-up is continuous and can genuinely adapt.",
    "คุยกับแพทย์":"Talk with the doctor",
    "แพทย์อ่านแบบประเมินและประวัติก่อนเริ่มปรึกษา":"The doctor reads your questionnaire and history before the consultation starts.",
    "เก็บแผนไว้ในโปรไฟล์":"Keep the plan in your profile",
    "ดูแผนการรักษา วิธีใช้ยา และนัดครั้งถัดไปได้เสมอ":"See your care plan, medicine instructions and next appointment at any time.",
    "ติดตามกับทีมเดิม":"Follow up with the same team",
    "กลับมาคุยต่อจากเดิม พร้อมรายงานผลและอาการข้างเคียง":"Continue the conversation where you left off and report progress or side effects.",
    "ปรับเมื่อจำเป็น":"Adjust when needed",
    "แพทย์ทบทวนผลแล้วปรับแผน ไม่ปล่อยให้คุณจัดการคนเดียว":"The doctor reviews your progress and adjusts the plan, so you are not left to manage it alone.",
    "สิ่งที่ควรรู้ก่อนเริ่ม":"What to know before you start",
    "จำเป็นต้องเปิดกล้องไหม":"Do I need to turn on my camera?",
    "แพทย์อาจขอข้อมูลที่จำเป็นต่อการประเมิน แต่คุณสามารถแจ้งข้อกังวลเรื่องความเป็นส่วนตัวก่อนเริ่มได้":"The doctor may request information needed for the assessment, but you can raise privacy concerns before you begin.",
    "แพทย์จะสั่งยาให้เลยไหม":"Will the doctor prescribe medicine straight away?",
    "ไม่เสมอไป แพทย์จะทบทวนสาเหตุ สุขภาพหัวใจ และยาที่ใช้อยู่ก่อนเลือกแนวทาง":"Not necessarily. The doctor reviews the cause, your heart health and current medicines before choosing an approach.",
    "ติดตามกับแพทย์คนเดิมได้ไหม":"Can I follow up with the same doctor?",
    "ระบบออกแบบให้เห็นประวัติและแผนเดิม เพื่อให้ทีมดูแลติดตามต่อจากข้อมูลครั้งก่อน":"The system keeps your history and existing plan visible so the care team can continue from your previous information.",
    "ไม่มีแผนสำเร็จรูป มีแต่แผนของคุณ":"No off-the-shelf plans, only yours",
    "แพทย์อ่านคำตอบของคุณทุกข้อก่อนการปรึกษา แล้วออกแบบแนวทางจากข้อมูลจริง ไม่ใช่จากแพ็กเกจที่ตั้งไว้ล่วงหน้า":"The doctor reads every answer before the consultation and builds an approach from real information, not from a pre-set package.",
    "ตอบแบบประเมินสุขภาพ":"Answer the health questionnaire",
    "คำถามปรับตามอาการที่คุณเลือก ตอบทีละข้ออย่างเป็นส่วนตัว":"Questions adapt to the concern you pick, one at a time and in private.",
    "แพทย์ทบทวนก่อนคุย":"The doctor reviews before you talk",
    "อ่านประวัติ ยาที่ใช้อยู่ และความเสี่ยง ก่อนเข้าห้องปรึกษา":"Your history, current medicines and risks are read before the consultation room opens.",
    "ได้แผนเฉพาะของคุณ":"Get a plan that is yours",
    "เลือกแนวทางจากข้อบ่งใช้และเป้าหมาย พร้อมเหตุผลที่อธิบายได้":"An approach chosen from the indications and your goals, with reasons that can be explained.",
    "ติดตามและปรับ":"Follow up and adjust",
    "ทบทวนผลและผลข้างเคียงเป็นระยะ แล้วปรับแผนเมื่อจำเป็น":"Results and side effects are reviewed periodically, and the plan changes when it needs to.",
    "สิ่งที่แพทย์จะประเมิน":"What the doctor will assess",
    "บทความเกี่ยวกับอาการนี้":"Articles about this concern",
    "อ่าน 6 นาที":"6 min read",
    "อ่าน 5 นาที":"5 min read",
    "อ่าน 4 นาที":"4 min read",
    "อ่าน 3 นาที":"3 min read",
    "หน้านี้ให้ข้อมูลทั่วไป ไม่ใช่การวินิจฉัย":"This page is general information, not a diagnosis",
    "หากมีอาการรุนแรง เกิดขึ้นฉับพลัน หรือรู้สึกไม่ปลอดภัย ควรไปห้องฉุกเฉินหรือโทร 1669 แทนการรอปรึกษาออนไลน์":"If symptoms are severe, come on suddenly, or you feel unsafe, go to an emergency department or call 1669 rather than waiting for an online consultation.",
    "เริ่มจากแบบประเมินสั้น ๆ":"Start with a short questionnaire",
    "ตอบทีละหนึ่งคำถามและพูดคุยกับแพทย์อย่างเป็นส่วนตัว":"One question at a time, then a private conversation with a doctor.",
    "© 2026 Krane Clinic · การรักษาและการสั่งยาขึ้นอยู่กับการประเมินของแพทย์":"© 2026 Krane Clinic · treatment and prescribing depend on a doctor's assessment",
    "ผลลัพธ์จากการติดตามอย่างต่อเนื่อง":"Results from continuous follow-up",
    "เดือนที่ 6":"Month 6",
    "เดือนที่ 4":"Month 4",
    "เดือนที่ 9":"Month 9",
    "ผู้รับบริการ อายุ 34":"Patient, age 34",
    "ผู้รับบริการ อายุ 41":"Patient, age 41",
    "ผู้รับบริการ อายุ 29":"Patient, age 29",
    "ติดตามกับแพทย์ทุก 8 สัปดาห์":"Doctor follow-up every 8 weeks",
    "ปรับแผนหลังการติดตามครั้งที่สอง":"Plan adjusted after the second follow-up",
    "ดูแลต่อเนื่องพร้อมปรับพฤติกรรม":"Ongoing care alongside behaviour change",
    "ภาพประกอบเป็นตัวอย่างระหว่างรอภาพเคสจริงที่ได้รับความยินยอม ·":"Illustrations stand in until consented photographs of real cases are available ·",
    "ผลลัพธ์แตกต่างกันในแต่ละบุคคล ขึ้นอยู่กับแผนการดูแลและการติดตามกับแพทย์":"results vary from person to person, depending on the care plan and follow-up with the doctor",
    "ผลลัพธ์แตกต่างกันในแต่ละบุคคล ขึ้นอยู่กับสาเหตุและแผนการดูแลของแพทย์":"results vary from person to person, depending on the cause and the doctor's care plan",
    "รูปแบบยาที่แพทย์อาจพิจารณา":"The forms of medicine a doctor may consider",
    "แพทย์เลือกรูปแบบและขนาดยาจากข้อบ่งใช้ เป้าหมาย และประวัติสุขภาพของคุณ":"The doctor chooses the form and dose from the indications, your goals and your health history.",
    "ลดน้ำหนักด้วยแผนที่แพทย์ออกให้คุณ":"Lose weight on a plan a doctor writes for you",
    "เริ่มจากการประเมินโดยแพทย์ที่มีใบอนุญาต แล้ววางแผนที่ทำต่อได้จริงในชีวิตคุณ":"Start with an assessment by a licensed doctor, then a plan you can actually keep to.",
    "น้ำหนักมีหลายปัจจัยมากกว่าตัวเลขบนตาชั่ง":"Weight is more than the number on the scale",
    "ฮอร์โมนความอิ่ม พันธุกรรม การนอน ยาที่ใช้อยู่ และภาวะสุขภาพ ล้วนกำหนดว่าร่างกายเก็บและใช้พลังงานอย่างไร นี่คือเหตุผลที่แผนเดียวกันไม่ได้ผลกับทุกคน":"Satiety hormones, genetics, sleep, the medicines you take and your health conditions all shape how your body stores and uses energy. That is why the same plan does not work for everyone.",
    "~1 ใน 3":"~1 in 3",
    "ผู้ใหญ่ไทยอยู่ในเกณฑ์น้ำหนักเกิน":"Thai adults are in the overweight range",
    "น้ำหนักที่ลดลงก็เริ่มเห็นผลต่อสุขภาพแล้ว":"of weight lost already shows health benefits",
    "12+ เดือน":"12+ months",
    "ระยะเวลาที่ควรติดตามผลอย่างต่อเนื่อง":"is how long follow-up should continue",
    "ส่วนสูง น้ำหนัก และการเปลี่ยนแปลงที่ผ่านมา":"Height, weight and how they have changed",
    "โรคประจำตัว ประวัติการผ่าตัด และยาที่ใช้อยู่":"Existing conditions, past surgery and current medicines",
    "ประวัติตับอ่อน ถุงน้ำดี ต่อมไทรอยด์ และการตั้งครรภ์":"Pancreas, gallbladder and thyroid history, and pregnancy",
    "เป้าหมาย พฤติกรรมอาหาร การนอน และการเคลื่อนไหว":"Goals, eating habits, sleep and movement",
    "ใช้ต่อเนื่อง":"Ongoing use",
    "ฉีดใต้ผิวหนังสัปดาห์ละครั้ง":"A subcutaneous injection once a week",
    "ปากกาฉีด GLP-1":"GLP-1 injection pen",
    "เช่น semaglutide หรือ tirzepatide":"such as semaglutide or tirzepatide",
    "ตามข้อบ่งใช้รายบุคคล":"By individual indication",
    "ยารับประทาน":"Oral medicine",
    "แพทย์พิจารณาเมื่อเหมาะกับสุขภาพและเป้าหมาย":"Considered when it suits your health and goals",
    "Semaglutide และ tirzepatide เป็นยาที่ต้องประเมินข้อบ่งใช้ ข้อห้ามใช้ และติดตามผลโดยแพทย์ ไม่เหมาะสำหรับทุกคน":"Semaglutide and tirzepatide require a doctor to assess indications and contraindications and to monitor treatment. They are not suitable for everyone.",
    "GLP-1 ทำงานอย่างไรกับความอยากอาหาร":"How GLP-1 works on appetite",
    "กลไกโดยย่อ ผลข้างเคียงที่พบบ่อย และเหตุผลที่ต้องค่อย ๆ ปรับขนาดยา":"The mechanism in brief, the common side effects, and why the dose is raised slowly.",
    "คุยเรื่องนี้กับแพทย์ได้ โดยไม่ต้องเดินเข้าคลินิก":"Talk to a doctor about it without walking into a clinic",
    "ประเมินออนไลน์อย่างเป็นส่วนตัว หาสาเหตุที่แท้จริง แล้วเลือกทางที่ปลอดภัยกับหัวใจของคุณ":"A private online assessment to find the real cause, then an option that is safe for your heart.",
    "ED มักเป็นสัญญาณของร่างกาย ไม่ใช่ความล้มเหลว":"ED is usually a signal from the body, not a failure",
    "การแข็งตัวต้องอาศัยหลอดเลือด เส้นประสาท ฮอร์โมน และสภาพจิตใจทำงานร่วมกัน เมื่อส่วนใดส่วนหนึ่งเปลี่ยนไป อาการจึงปรากฏ และบ่อยครั้งมาก่อนโรคหัวใจหลายปี":"An erection depends on blood vessels, nerves, hormones and state of mind working together. When one of them changes, symptoms appear — often years before heart disease does.",
    "ผู้ชายอายุ 40–70 ปีเคยมีอาการในระดับหนึ่ง":"of men aged 40–70 have had it to some degree",
    "3–5 ปี":"3–5 years",
    "ED อาจมาก่อนอาการโรคหลอดเลือดหัวใจ":"is how far ED can precede coronary symptoms",
    "ตอบสนองต่อการรักษาเมื่อประเมินสาเหตุถูกต้อง":"respond to treatment when the cause is assessed correctly",
    "อาการเริ่มเมื่อไร เกิดทุกครั้งหรือเป็นบางครั้ง":"When it started, and whether it happens every time or sometimes",
    "โรคหัวใจ ความดัน เบาหวาน และระดับไขมัน":"Heart disease, blood pressure, diabetes and lipid levels",
    "ยาที่ใช้อยู่ โดยเฉพาะยากลุ่ม nitrate":"Current medicines, nitrates in particular",
    "ความต้องการทางเพศ อาการตอนตื่นนอน และปัจจัยด้านอารมณ์":"Libido, morning erections and emotional factors",
    "ระยะเวลาออกฤทธิ์และขนาดยาต้องเลือกจากสุขภาพหัวใจและยาที่คุณใช้อยู่":"Duration of action and dose are chosen from your heart health and the medicines you already take.",
    "ใช้เมื่อจำเป็น":"As needed",
    "รับประทานก่อนมีกิจกรรม":"Taken before activity",
    "ยากลุ่ม PDE5":"PDE5 inhibitors",
    "เช่น sildenafil หรือ tadalafil เมื่อไม่มีข้อห้ามใช้":"such as sildenafil or tadalafil, where there is no contraindication",
    "สำหรับบางกรณีตามการประเมิน":"For some cases, on assessment",
    "ขนาดต่ำรายวัน":"Low daily dose",
    "แพทย์พิจารณาเมื่อเหมาะกับรูปแบบอาการ":"Considered when it suits the pattern of symptoms",
    "ห้ามใช้ sildenafil หรือ tadalafil ร่วมกับยากลุ่ม nitrate และยาทั้งสองอาจไม่เหมาะกับผู้มีภาวะหัวใจบางชนิด แพทย์ต้องประเมินก่อนสั่งใช้":"Never take sildenafil or tadalafil with a nitrate. Neither is suitable for some heart conditions, and a doctor must assess you before prescribing.",
    "สุขภาพผู้ชาย":"Men's health",
    "ED อาจเป็นสัญญาณของสุขภาพหลอดเลือด":"ED can be a sign of vascular health",
    "ทำไมแพทย์จึงถามเรื่องความดัน เบาหวาน และไขมัน ก่อนพิจารณายา":"Why a doctor asks about blood pressure, diabetes and lipids before considering medicine.",
    "ยากลุ่ม PDE5 ต่างกันอย่างไร":"How the PDE5 inhibitors differ",
    "ระยะเวลาออกฤทธิ์ ข้อห้ามใช้ที่สำคัญ และสิ่งที่ต้องบอกแพทย์เสมอ":"Duration of action, the contraindications that matter, and what to always tell your doctor.",
    "หากมีอาการเจ็บหน้าอก หายใจไม่ออก อ่อนแรงเฉียบพลัน หรือการแข็งตัวนานเกิน 4 ชั่วโมง ให้ไปห้องฉุกเฉินหรือโทร 1669 ทันที":"Chest pain, breathlessness, sudden weakness, or an erection lasting more than 4 hours: go to an emergency department or call 1669 immediately.",
    "กลับไปดูทีมแพทย์":"Back to the doctors",
    "ทีมแพทย์ Krane":"Krane doctors",
    "ความเชี่ยวชาญ":"Specialty",
    "การศึกษาและการอบรม":"Education and training",
    "ข้อมูลการศึกษาอยู่ระหว่างการตรวจสอบและอัปเดต":"Education details are being verified and updated",
    "ขอบเขตการดูแล":"Scope of care",
    "ดูแลและให้คำปรึกษาด้านตจวิทยา (ผิวหนัง) โดยพิจารณาจากข้อมูลสุขภาพและแบบประเมินของผู้รับบริการ":"Provides dermatology care and advice, based on the patient's health information and questionnaire.",
    "รูปแบบการปรึกษา":"How the consultation works",
    "แพทย์จะทบทวนข้อมูลก่อนเริ่มนัดหมาย และให้คำปรึกษาผ่านระบบออนไลน์ที่เป็นส่วนตัว":"The doctor reviews your information before the appointment and consults through a private online session.",
    "ความเหมาะสมทางคลินิก":"Clinical suitability",
    "หากการปรึกษาทางไกลไม่เหมาะกับอาการ แพทย์อาจแนะนำการตรวจเพิ่มเติมหรือการพบแพทย์ด้วยตนเอง":"If a remote consultation does not suit your symptoms, the doctor may recommend further tests or an in-person visit.",
    "วิธีที่เราทำงานร่วมกัน":"How we work together",
    "ทีมแพทย์ร่วมออกแบบ":"The doctors shape",
    "การดูแลของ Krane อย่างไร":"how Krane cares for you",
    "ทุกขั้นตอนเริ่มจากข้อมูลสุขภาพจริงของผู้รับบริการ และผ่านการพิจารณาทางการแพทย์ก่อนเสนอทางเลือกที่เหมาะสม":"Every step starts from the patient's real health information and is reviewed clinically before any option is offered.",
    "แบบประเมินช่วยรวบรวมอาการ ประวัติสุขภาพ เป้าหมาย และข้อมูลสำคัญ เพื่อให้ทีมแพทย์เห็นภาพรวมก่อนเริ่มการปรึกษา":"The questionnaire gathers symptoms, health history, goals and other key details so the doctors see the whole picture before the consultation.",
    "แพทย์ซักถามเพิ่มเติม อธิบายประโยชน์ ข้อควรระวัง และทางเลือกที่เป็นไปได้ โดยการสั่งยาขึ้นอยู่กับความเหมาะสมทางคลินิกของแต่ละคน":"The doctor asks further questions and explains the benefits, the cautions and the possible alternatives. Whether medicine is prescribed depends on what is clinically appropriate for each person.",
    "หลังเริ่มการดูแล ทีมแพทย์ใช้ข้อมูลติดตามผลเพื่อประเมินความคืบหน้า ความปลอดภัย และปรับแผนเมื่อสุขภาพหรือเป้าหมายของคุณเปลี่ยนไป":"Once care has started, the doctors use follow-up data to judge progress and safety, and adjust the plan when your health or goals change.",
    "หน้ารายละเอียดแพทย์":"Doctor profile page",
    "Krane Clinic หน้าหลัก":"Krane Clinic home",
    "ข้อมูลการดูแล":"Care information",
    "คณะที่ปรึกษาทางการแพทย์":"Medical advisory board",
    "หน้าแยกสำหรับอธิบายบทบาทของที่ปรึกษา ซึ่งแตกต่างจากแพทย์ผู้ให้คำปรึกษากับผู้รับบริการโดยตรง":"A separate page explaining the advisers' role, which differs from that of the doctors who consult with patients directly.",
    "รอข้อมูลที่ปรึกษาจริงจากลูกค้า":"Awaiting the real adviser details from the client",
    "บทบาท":"Role",
    "ขอบเขตการกำกับคุณภาพทางการแพทย์":"Scope of medical quality oversight",
    "การทบทวนแนวทางการดูแล":"Review of care guidelines",
    "ความเกี่ยวข้องกับบริการแต่ละด้าน":"Relevance to each service area",
    "ประวัติ":"Background",
    "มหาวิทยาลัยและวุฒิการศึกษา":"University and qualifications",
    "ตำแหน่งและประสบการณ์ปัจจุบัน":"Current position and experience",
    "ผลงานหรือองค์กรที่อนุญาตให้เผยแพร่":"Publications or organisations cleared for publication",
    "สาขาที่ให้คำปรึกษากับ Krane":"Areas advised on for Krane",
    "ประสบการณ์ที่เกี่ยวข้องกับ telemedicine":"Relevant telemedicine experience",
    "ภาษาและพื้นที่ที่ให้คำแนะนำ":"Languages and regions advised",
    "หน้านี้เป็นโครงสร้างสำหรับทดสอบการนำเสนอข้อมูล ไม่อ้างว่าที่ปรึกษาเป็นผู้ตรวจหรือรักษาผู้รับบริการ เว้นแต่ลูกค้ายืนยันบทบาทนั้นอย่างชัดเจน":"This page is a structure for testing how the information reads. It does not claim that advisers examine or treat patients unless the client confirms that role explicitly.",
    "หน้ารายละเอียดที่ปรึกษา":"Adviser profile page",
    "ข้อมูลที่ปรึกษาที่ต้องใช้":"Adviser details still needed",
    "พส":"PS",
    "ชห":"CH",
    /* Hero, service carousel and the scrolling line, added when the client's own
     English in the copy doc gave the wording for the headline (14 Sep). The
     headline and lead each break across two lines, so every fragment is its own
     text node and needs its own entry. */
    "แพทย์ประจำตัวที่":"Your personal doctor,",
    "คอยดูแลคุณ":"by your side",
    "ปรึกษาแพทย์ทางไกล พร้อมรับยาตามใบสั่งแพทย์":"Telehealth consultations with prescription medicine",
    "ส่งตรงถึงบ้าน":"delivered to your door",
    "โปรแกรมลดน้ำหนัก":"Weight loss programme",
    "โปรแกรมฟื้นฟูเส้นผม":"Hair recovery programme",
    "โปรแกรมฟื้นฟูสมรรถภาพเพศชาย":"Sexual health programme",
    /* Product cards: weight */
    "ออกฤทธิ์สองทาง ช่วยคุมความอยากอาหารและระดับน้ำตาล":"Works two ways, helping control appetite and blood sugar",
    "ช่วยให้อิ่มนานขึ้น ลดความอยากอาหารระหว่างวัน":"Keeps you full for longer and reduces appetite through the day",
    "เซมากลูไทด์ขนาดที่ออกแบบมาเพื่อการจัดการน้ำหนักโดยเฉพาะ":"Semaglutide at a dose designed specifically for weight management",
    "เซมากลูไทด์ชนิดรับประทาน สำหรับผู้ที่ไม่สะดวกฉีด":"Semaglutide in tablet form, for anyone who would rather not inject",
    /* Product cards: hair */
    "ลดฮอร์โมน DHT ซึ่งเป็นสาเหตุของผมร่วงตามพันธุกรรม":"Lowers DHT, the hormone behind hereditary hair loss",
    "ฟินาสเตอไรด์ทางเลือก ออกฤทธิ์แบบเดียวกับสูตรต้นแบบ":"An alternative finasteride that works the same way as the original",
    "สูตรต้นแบบของฟินาสเตอไรด์สำหรับผมร่วงในผู้ชาย":"The original finasteride for male hair loss",
    "ไมนอกซิดิลชนิดรับประทาน สำหรับผู้ที่ไม่สะดวกใช้ยาทา":"Minoxidil in tablet form, for anyone who would rather not use a topical",
    "ยาทาเฉพาะจุด ช่วยกระตุ้นการไหลเวียนที่หนังศีรษะ":"A topical that stimulates circulation at the scalp",
    "โลชั่นไมนอกซิดิล เนื้อบางเบา ใช้ได้ทุกวัน":"A light minoxidil lotion you can use every day",
    /* Before-and-after captions on the result pairs */
    "หลัง 3 เดือน":"After 3 months",
    "หลัง 4 เดือน":"After 4 months",
    "หลัง 6 เดือน":"After 6 months",
    "หลัง 9 เดือน":"After 9 months",
    "หลัง 12 เดือน":"After 12 months",
    /* The scrolling "what you no longer have to do" line */
    "สิ่งที่คุณไม่ต้องทำอีกต่อไป":"What you no longer have to do",
    "ไม่ต้องเดินทางไปคลินิก":"No trip to the clinic",
    "ไม่ต้องต่อคิวรอพบแพทย์":"No queue to see a doctor",
    "ไม่ต้องลางานทั้งวัน":"No day off work",
    "คุยกับแพทย์ตัวจริง":"Talk to a real doctor",
    "ยาส่งถึงบ้าน":"Medicine delivered to your door",
    /* ISO lines on the trust cards, and the programme card action */
    "มาตรฐานการจัดการความมั่นคงปลอดภัยของข้อมูล":"Information security management standard",
    "มาตรฐานการคุ้มครองข้อมูลส่วนบุคคลบนคลาวด์":"Personal data protection in the cloud standard",
    "มาตรฐานการบริหารจัดการบริการไอที โดย INET":"IT service management standard, by INET",
    "เริ่ม":"Start",
    /* Doctors index and the shared section kickers on the condition pages. */
    "แพทย์ที่ดูแลคุณ":"The doctors who look after you",
    "อ่านต่ออย่างเข้าใจ":"Read on with context",
    "อายุรศาสตร์ · อนุสาขาโรคระบบการหายใจ":"Internal medicine · Respiratory medicine subspecialty",
    "อายุรศาสตร์ · อนุสาขาโภชนศาสตร์คลินิก":"Internal medicine · Clinical nutrition subspecialty",
    /* Condition pages: the section rail and the kickers above each block. */
    "ส่วนต่าง ๆ ของหน้าข้อมูลการดูแล":"Sections of this care information page",
    "ภาพรวม":"Overview",
    "เหมาะกับใคร":"Who it suits",
    "ขั้นตอนการดูแล":"How care works",
    "ทางเลือกการรักษา":"Treatment options",
    "การติดตาม":"Follow-up",
    "คำถามที่พบบ่อย":"Common questions",
    "เข้าใจอาการให้ตรงจุด":"Understand the concern precisely",
    "เช็กความเหมาะสมเบื้องต้น":"A first check on whether it suits you",
    "แผนที่เริ่มจากคุณ":"A plan that starts with you",
    "เปรียบเทียบทางเลือก":"Compare the options",
    "การดูแลไม่จบหลังการปรึกษา":"Care does not end with the consultation",
    /* Condition pages: hero kickers, and the closing kicker derived from each. */
    "ดูแลน้ำหนักกับแพทย์":"Weight care with a doctor",
    "ดูแลภาวะ ED อย่างเป็นส่วนตัว":"Private care for ED",
    "สุขภาพทางเพศแบบเป็นส่วนตัว":"Sexual health, privately",
    "ฟื้นฟูเส้นผม":"Hair recovery",
    "ผิวพรรณ & ชะลอวัย":"Skin & ageing",
    "ฮอร์โมน & TRT":"Hormones & TRT",
    "การนอนและความเครียด":"Sleep and stress",
    "พร้อมเริ่มดูแลน้ำหนักกับแพทย์":"Ready to start weight care with a doctor",
    "พร้อมเริ่มดูแลภาวะ ED อย่างเป็นส่วนตัว":"Ready to start private care for ED",
    "พร้อมเริ่มดูแลสุขภาพทางเพศแบบเป็นส่วนตัว":"Ready to start sexual health care, privately",
    "พร้อมเริ่มดูแลฟื้นฟูเส้นผม":"Ready to start hair recovery",
    "พร้อมเริ่มดูแลผิวพรรณ & ชะลอวัย":"Ready to start skin & ageing care",
    "พร้อมเริ่มดูแลฮอร์โมน & TRT":"Ready to start hormone & TRT care",
    "พร้อมเริ่มดูแลการนอนและความเครียด":"Ready to start sleep and stress care",
    /* Condition pages: the two-option comparison table. */
    "เปรียบเทียบ 2 ทางเลือก":"Two options compared",
    "ดูรูปแบบการใช้และข้อพิจารณาของแต่ละทางเลือก ก่อนคุยกับแพทย์เพื่อเลือกแผนที่เหมาะกับคุณ":"See how each option is used and what it involves, before talking to a doctor about the plan that suits you.",
    "ทางเลือก":"Option",
    "เทียบทีละข้อ":"Point by point",
    "ตารางเปรียบเทียบทางเลือกการดูแล":"Care options comparison table",
    "วิธีใช้":"How it is used",
    "รูปแบบการดูแล":"Form of care",
    "แพทย์พิจารณาจาก":"The doctor considers",
    "สิ่งที่ควรรู้":"What to know",
    "โรคประจำตัว ยาที่ใช้อยู่ และความเสี่ยงเฉพาะบุคคล":"Existing conditions, current medicines and individual risk",
    "ข้อบ่งใช้ ข้อห้าม และการติดตามหลังเริ่มยา":"Indications, contraindications and follow-up once treatment starts",
    "ตำแหน่งที่ใช้ ความไวของผิว และอาการระคายเคือง":"Where it is applied, skin sensitivity and irritation",
    "ผลตรวจ ข้อห้าม และแผนติดตามเป็นระยะ":"Test results, contraindications and a periodic follow-up plan",
    "ข้อมูลนี้ใช้เพื่อช่วยทำความเข้าใจเบื้องต้น ทางเลือกจริงขึ้นอยู่กับข้อบ่งใช้ ข้อห้าม และการประเมินของแพทย์":"This is background to help you understand the options. What is actually available depends on the indications, the contraindications and the doctor's assessment.",
    /* Condition pages: product cards, their thumbnails and tags. */
    "ภาพผลิตภัณฑ์":"Product photo",
    "ภาพระยะใกล้":"Close-up photo",
    "ภาพอีกมุม":"Another angle",
    "เลือกรูปภาพ ยากลุ่ม PDE5":"Choose a photo, PDE5 medicines",
    "เลือกรูปภาพ ขนาดต่ำรายวัน":"Choose a photo, low daily dose",
    "เลือกรูปภาพ ปากกาฉีด GLP-1":"Choose a photo, GLP-1 injection pen",
    "เลือกรูปภาพ ยารับประทาน":"Choose a photo, oral medicine",
    "เลือกรูปภาพ ยาทาเฉพาะที่":"Choose a photo, topical medicine",
    "เลือกรูปภาพ ฮอร์โมนตามใบสั่งแพทย์":"Choose a photo, prescription hormones",
    "เลือกรูปภาพ ผลิตภัณฑ์สนับสนุนผิว":"Choose a photo, supporting skin products",
    "เลือกรูปภาพ การดูแลปัจจัยร่วม":"Choose a photo, contributing-factor care",
    "ยาทาเฉพาะที่":"Topical medicine",
    "ฮอร์โมนตามใบสั่งแพทย์":"Prescription hormones",
    "ผลิตภัณฑ์สนับสนุนผิว":"Supporting skin products",
    "การดูแลปัจจัยร่วม":"Contributing-factor care",
    "ใช้เสริม":"Supporting",
    "ไม่ใช้ยา":"No medicine",
    "ทาบาง ๆ ก่อนนอน":"A thin layer before bed",
    "ใช้ร่วมกับแผนแพทย์":"Alongside the doctor's plan",
    "ใช้เฉพาะเมื่อวินิจฉัยชัดเจน":"Only once the diagnosis is clear",
    "การนอน น้ำหนัก และยาที่ใช้":"Sleep, weight and current medicines",
    "เลือกสารออกฤทธิ์ตามปัญหาผิว":"Active ingredients chosen for your skin concern",
    "เนื้อยา ความเข้มข้น และความถี่ต้องเหมาะกับปัญหาและความไวของผิว":"The base, the strength and how often it is used all have to suit the concern and how sensitive the skin is.",
    "จัดกิจวัตรให้ผิวทนต่อสารออกฤทธิ์ได้":"A routine that lets the skin tolerate active ingredients",
    "พร้อมแผนติดตามผลเลือดเป็นระยะ":"With a plan for periodic blood tests",
    "หลายกรณีอาการดีขึ้นโดยไม่ต้องใช้ฮอร์โมน":"In many cases symptoms improve without hormones",
    /* Condition pages: who the programme suits, and what the doctor asks for. */
    "ต้องการประเมินน้ำหนักและความเสี่ยงสุขภาพอย่างเป็นระบบ":"Want weight and health risk assessed systematically",
    "ต้องการประเมินอาการกับแพทย์อย่างเป็นส่วนตัว":"Want the concern assessed privately with a doctor",
    "ต้องการแผนที่อ้างอิงจากประวัติสุขภาพจริง":"Want a plan grounded in a real health history",
    "พร้อมติดตามผลและปรับแผนร่วมกับแพทย์":"Ready to follow up and adjust the plan with a doctor",
    "พร้อมติดตามผลและปรับแผนเมื่อจำเป็น":"Ready to follow up and adjust the plan when needed",
    "เคยลองปรับพฤติกรรมแล้วแต่ผลไม่ต่อเนื่อง":"Have tried changing habits but the results did not hold",
    "กำลังตั้งครรภ์ ให้นมบุตร หรือวางแผนตั้งครรภ์":"Pregnant, breastfeeding or planning a pregnancy",
    "กำลังตั้งครรภ์ ให้นมบุตร หรือใช้ยาหลายชนิด":"Pregnant, breastfeeding or taking several medicines",
    "มีประวัติตับอ่อน ถุงน้ำดี หรือโรคต่อมไทรอยด์บางชนิด":"A history of pancreatic, gallbladder or certain thyroid conditions",
    "มีอาการรุนแรงหรือเกิดขึ้นฉับพลัน":"Severe or sudden symptoms",
    "มีโรคประจำตัวหรืออาการที่ยังไม่เคยตรวจ":"An existing condition or symptoms never investigated",
    "ใช้ยา หรือมีโรคประจำตัวที่อาจกระทบการรักษา":"Taking medicines, or with a condition that could affect treatment",
    "อาการ ระยะเวลา และผลกระทบต่อชีวิตประจำวัน":"Symptoms, how long they have lasted and the effect on daily life",
    "อาการหลัก ตำแหน่ง ระยะเวลา และภาพถ่ายที่ชัดเจน":"The main symptoms, where they are, how long they have lasted and clear photos",
    "การนอน น้ำหนัก การออกกำลัง และความเครียด":"Sleep, weight, exercise and stress",
    "ประวัติภาวะเจริญพันธุ์ ต่อมลูกหมาก หัวใจ และลิ่มเลือด":"History of fertility, prostate, heart and blood-clotting conditions",
    "ประวัติแพ้ ระคายเคือง ตั้งครรภ์ หรือให้นมบุตร":"History of allergies, irritation, pregnancy or breastfeeding",
    "ผลิตภัณฑ์และยาทุกชนิดที่ใช้อยู่":"Every product and medicine currently in use",
    "ยา อาหารเสริม การใช้ฮอร์โมนหรือสารกระตุ้นที่ผ่านมา":"Medicines, supplements and any past hormone or stimulant use",
    "เป้าหมายและเวลาที่พร้อมติดตามผล":"Your goals and the time you can give to follow-up",
    /* Condition pages: follow-up, safety and the FAQ. */
    "ประวัติและแผนการดูแลถูกออกแบบให้อยู่ในโปรไฟล์ เพื่อใช้ประกอบการติดตามครั้งถัดไป":"Your history and care plan are kept in your profile so they inform the next follow-up.",
    "แพทย์จะนัดทบทวนผล อาการข้างเคียง และปรับแผนตามความเหมาะสมของแต่ละคน":"The doctor books a review of results and side effects, and adjusts the plan to suit each person.",
    "ข้อมูลความปลอดภัยที่สำคัญ":"Important safety information",
    "สิ่งที่ควรรู้ก่อนเริ่มการดูแลและใช้ยาตามแผนของแพทย์":"What to know before starting care and taking medicine to a doctor's plan",
    "อ่านเพิ่มเติม":"Read more",
    "อ่านข้อมูลความปลอดภัย":"Read the safety information",
    "ต้องใช้ยาทุกคนไหม":"Does everyone need medicine?",
    "ไม่จำเป็น แพทย์จะเริ่มจากเป้าหมาย ประวัติสุขภาพ และสิ่งที่คุณเคยลอง ก่อนพิจารณาว่ายาช่วยได้หรือไม่":"Not necessarily. The doctor starts from your goals, your health history and what you have already tried, before considering whether medicine would help.",
    "ปรึกษาออนไลน์เหมาะกับทุกอาการไหม":"Is an online consultation right for every concern?",
    "ไม่ทุกอาการ หากข้อมูลบ่งชี้ว่าต้องตรวจร่างกายหรือตรวจเพิ่มเติม แพทย์จะแนะนำให้พบสถานพยาบาล":"Not every one. If your answers point to a need for a physical examination or further tests, the doctor will refer you to a clinic.",
    "ระบบสั่งยาให้อัตโนมัติไหม":"Does the system prescribe automatically?",
    "ไม่ การสั่งยาเกิดขึ้นเมื่อแพทย์ประเมินแล้วว่าเหมาะสมเท่านั้น":"No. Medicine is only prescribed once a doctor has assessed that it is appropriate.",
    "จะรู้ค่าใช้จ่ายเมื่อไร":"When will I know the cost?",
    "ระบบจะแสดงค่าปรึกษา ค่ายา และค่าจัดส่งแยกรายการให้ตรวจสอบก่อนชำระเงิน":"The consultation fee, the medicine and the delivery are itemised for you to check before you pay.",
    "ข้อมูลครั้งก่อนหายไหม":"Is my earlier information lost?",
    "ถ้าเริ่มยาแล้วต้องติดตามอย่างไร":"What follow-up is there once treatment starts?",
    /* Condition pages: knowledge blocks and their stat callouts. */
    "ก่อนจะเริ่ม TRT ต้องรู้ให้แน่ก่อนว่าใช่":"Before starting TRT, be sure it is the right answer",
    "อาการอย่างเดียวยังยืนยันภาวะฮอร์โมนต่ำไม่ได้":"Symptoms alone cannot confirm low hormones",
    "ระดับเทสโทสเตอโรนเปลี่ยนตามเวลาของวัน การนอน น้ำหนัก และความเจ็บป่วย ผลตรวจครั้งเดียวจึงไม่พอ และหลายอาการที่คล้ายฮอร์โมนต่ำมาจากสาเหตุที่รักษาง่ายกว่า":"Testosterone moves with the time of day, sleep, weight and illness, so a single test is not enough — and many symptoms that look like low hormones come from causes that are easier to treat.",
    "ความเหนื่อยล้า สมรรถภาพลดลง หรือมวลกล้ามเนื้อเปลี่ยน มีได้หลายสาเหตุ การตรวจยืนยันจึงมาก่อนการรักษา":"Fatigue, reduced performance or a change in muscle mass can have many causes, so confirming with tests comes before treatment.",
    "รูปแบบการรักษาที่ต้องวินิจฉัยก่อน":"A treatment that needs a diagnosis first",
    "TRT พิจารณาเฉพาะผู้ที่มีอาการและผลตรวจสอดคล้องกัน พร้อมแผนติดตามความปลอดภัย":"TRT is only considered where symptoms and test results agree, with a safety follow-up plan in place.",
    "TRT ต้องติดตามความปลอดภัยเป็นระยะ":"TRT needs periodic safety monitoring",
    "TRT ไม่ใช่ผลิตภัณฑ์ชะลอวัยทั่วไป ต้องมีการวินิจฉัยที่เหมาะสมและติดตามความปลอดภัยโดยแพทย์":"TRT is not a general anti-ageing product. It requires a proper diagnosis and safety monitoring by a doctor.",
    "จำนวนผลตรวจที่ควรยืนยันก่อนวินิจฉัย":"Test results needed to confirm a diagnosis",
    "ช่วงเวลาที่ควรเจาะเลือดเพื่อผลที่แม่นยำ":"When to take blood for an accurate result",
    "2 ครั้ง":"Two",
    "ตอนเช้า":"Morning",
    "ตลอดการรักษา":"Throughout treatment",
    /* Condition pages: the skin knowledge block. */
    "ผิวที่ดูคล้ายกัน อาจต้องการคนละแผน":"Skin that looks alike can need different plans",
    "ตำแหน่งและลักษณะบอกสาเหตุได้มาก":"Where it appears and how it looks say a lot about the cause",
    "สิวที่กราม สิวที่หน้าผาก รอยแดงหลังสิว และจุดด่างดำจากแดด มีกลไกต่างกัน การเลือกสารออกฤทธิ์ผิดจึงทำให้ผิวแย่ลงได้ แม้จะเป็นผลิตภัณฑ์ที่ดี":"Acne along the jaw, acne on the forehead, redness after a breakout and sun-related dark spots all work differently. Choosing the wrong active can make skin worse, even with a good product.",
    "สิว รอยดำ ความไวของผิว และริ้วรอยมีหลายปัจจัย แพทย์ประเมินก่อนแนะนำสารออกฤทธิ์ที่เหมาะกับผิวคุณ":"Acne, dark marks, sensitivity and fine lines have many contributing factors. A doctor assesses them before recommending the actives that suit your skin.",
    "ยาทาบางชนิดรวมถึง retinoids มีข้อควรระวัง โดยเฉพาะระหว่างตั้งครรภ์หรือวางแผนตั้งครรภ์ ควรให้แพทย์ประเมินก่อนใช้":"Some topicals, retinoids included, carry precautions — particularly during pregnancy or when planning one. Have a doctor assess before you start.",
    "ปัจจัยเดียวที่ช่วยได้แทบทุกปัญหาผิว":"The one factor that helps almost every skin concern",
    "ช่วงที่ผิวต้องปรับตัวกับสารออกฤทธิ์ใหม่":"How long skin takes to adjust to a new active",
    "เพิ่มสารออกฤทธิ์ทีละตัวเพื่อหาสาเหตุการระคายเคือง":"Add one active at a time so irritation can be traced",
    "SPF ทุกวัน":"SPF daily",
    "4–12 สัปดาห์":"4-12 weeks",
    "ทีละอย่าง":"One at a time",
    /* Condition pages: the article rail. */
    "ผิวพรรณ":"Skin",
    "ฮอร์โมน":"Hormones",
    "เริ่มใช้ retinoids โดยไม่ทำให้ผิวพัง":"Starting retinoids without wrecking your skin",
    "ความเข้มข้น ความถี่ และช่วงปรับตัวของผิวที่ควรรู้ก่อนเริ่ม":"The strength, the frequency and the adjustment period to know about before you start",
    "นิสัยดี ๆ เพื่อสุขภาพผมและผิว":"Habits that keep hair and skin healthy",
    "การนอน อาหาร และความเครียด ส่งผลกับเส้นผมและผิวมากกว่าที่คิด":"Sleep, food and stress affect hair and skin more than most people expect",
    "อาการเหนื่อยล้าไม่ได้แปลว่าฮอร์โมนต่ำเสมอไป":"Fatigue does not always mean low hormones",
    "สาเหตุอื่นที่ต้องคัดกรองก่อน และเหตุผลที่ต้องตรวจยืนยันก่อน TRT":"The other causes to rule out first, and why TRT needs confirmed tests"
  };

  var pending = false, mo = null, ownsLang = false;

  /* Two of these pages (doctor and adviser profiles) carry no language control
     and no header script, so nothing ever set <html lang> on them and they
     stayed Thai whatever the reader had chosen. Where no other handler owns the
     language, this module reads the same stored choice the rest of the site
     uses — Thai unless English was explicitly picked — and sets it. */
  function prefersEnglish() {
    try { if (localStorage.getItem("krane_lang") === "en") return true; } catch (e) {}
    return /[?&#]lang=en\b/.test(location.href);
  }
  function isEnglish() {
    return ownsLang ? prefersEnglish() : document.documentElement.lang === "en";
  }

  function walk(en) {
    var w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode: function (n) {
        var p = n.parentNode && n.parentNode.nodeName;
        return (p === "SCRIPT" || p === "STYLE" || p === "NOSCRIPT") ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
      }
    });
    var nodes = [], n;
    while ((n = w.nextNode())) nodes.push(n);
    nodes.forEach(function (node) {
      if (en) {
        var key = (node.__thSrc !== undefined ? node.__thSrc : node.nodeValue).trim();
        if (EN[key] !== undefined) {
          if (node.__thSrc === undefined) node.__thSrc = node.nodeValue;
          node.nodeValue = node.__thSrc.replace(key, EN[key]);
        }
      } else if (node.__thSrc !== undefined) {
        node.nodeValue = node.__thSrc;
        delete node.__thSrc;
      }
    });
    document.querySelectorAll("[placeholder]").forEach(function (el) {
      var th = el.getAttribute("data-ph-th");
      if (en) {
        var p = (th || el.getAttribute("placeholder") || "").trim();
        if (EN[p] !== undefined) { if (!th) el.setAttribute("data-ph-th", el.getAttribute("placeholder")); el.setAttribute("placeholder", EN[p]); }
      } else if (th) { el.setAttribute("placeholder", th); el.removeAttribute("data-ph-th"); }
    });
    document.querySelectorAll("[aria-label]").forEach(function (el) {
      var th = el.getAttribute("data-al-th");
      if (en) {
        var a = (th || el.getAttribute("aria-label") || "").trim();
        if (EN[a] !== undefined) { if (!th) el.setAttribute("data-al-th", el.getAttribute("aria-label")); el.setAttribute("aria-label", EN[a]); }
      } else if (th) { el.setAttribute("aria-label", th); el.removeAttribute("data-al-th"); }
    });
  }

  function observeOff() { if (mo) mo.disconnect(); }
  function observeOn() { if (mo) mo.observe(document.body, { childList: true, subtree: true, characterData: true }); }

  function apply() {
    var en = isEnglish();
    if (ownsLang) document.documentElement.lang = en ? "en" : "th";
    observeOff();
    walk(en);
    observeOn();
  }

  function schedule() {
    if (pending) return;
    pending = true;
    requestAnimationFrame(function () { pending = false; apply(); });
  }

  function boot() {
    ownsLang = !document.querySelector("[data-language], [data-lang] .lang__opt, .lang .lang__opt");
    if (window.MutationObserver) mo = new MutationObserver(schedule);
    apply();
    /* The page's own language handler runs first and changes <html lang>; both
       of those are watched so this pass always lands after it. */
    new MutationObserver(schedule).observe(document.documentElement, { attributes: true, attributeFilter: ["lang"] });
    document.addEventListener("krane:languagechange", schedule);
    document.addEventListener("change", function (e) {
      if (e.target && e.target.matches && e.target.matches("[data-language]")) schedule();
    });
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();
